# destination: ./_site
destination: ./_site
# SITE TITLE
title: Rita Gil Pires

# URLS
#host: 0.0.0.0
#port: 4011
baseurl: /
url: http://ritagilpires.pt/

# ASSETS PATHS
images_url: assets/img/
js_url: assets/js/
css_url: assets/css/
fonts_url: assets/font/
